# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

#trigger:
# - feature/performace-m5

pool:
  vmImage: 'ubuntu-latest'

variables:  
  # Environment name  Cache Maven local repo
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

steps:
    - task: Cache@2
      inputs:
        key: 'maven | "$(Agent.OS)" | **/pom.xml'
        restoreKeys: |
          maven | "$(Agent.OS)"
          maven
        path: $(MAVEN_CACHE_FOLDER)
      displayName: Cache Maven local repo

    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        goals: 'package'
        mavenPomFile: './pom.xml'
        mavenOptions: '-Xmx3072m  $(MAVEN_OPTS)'
        options: '-Dmaven.test.skip=true -Dfile.encoding=UTF-8 --settings settings.xml -DaltDeploymentRepository=bcrm2::default::https://pkgs.dev.azure.com/iisiD200542-a-m/_packaging/bcrm2/maven/v1'
        publishJUnitResults: false
        #testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: true
        effectivePomSkip: false
        checkStyleRunAnalysis: false
        pmdRunAnalysis: false
        findBugsRunAnalysis: false